name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Context info
        run: |
          echo "ğŸ‰ Triggered by: ${{ github.event_name }}"
          echo "ğŸ§ Runner OS: ${{ runner.os }}"
          echo "ğŸ” Branch: ${{ github.ref }} | Repo: ${{ github.repository }}"

      - name: Print public IP
        run: |
          echo "Server Public IP:"
          curl -s https://api.ipify.org
          echo

      - name: List files
        run: |
          echo "Repository file list:"
          ls -alR "${{ github.workspace }}"

      - run: echo "ğŸ Job status is ${{ job.status }}."
